from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.portal_search_view, name='portal_search'),
    path('chatbot/ask/', views.chatbot_ask_view, name='chatbot_ask'),
    path('players/', views.players_view, name='players'),
    path('players/<str:player_id>/graph-photo/', views.player_graph_photo_view, name='player_graph_photo'),
    path('players/<str:player_id>/rdf/', views.player_detail_rdf_view, name='player_detail_rdf'),
    path('players/<str:player_id>/', views.player_detail_view, name='player_detail'),
    path('teams/', views.teams_view, name='teams'),
    path('teams/league/<str:league_code>/', views.league_detail_view, name='league_detail'),
    path('teams/<str:franchise_id>/', views.team_detail_view, name='team_detail'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('quiz/', views.quiz_view, name='quiz'),
    path('quiz/play/', views.quiz_play_view, name='quiz_play'),
    path('quiz/api/start/', views.quiz_start_api_view, name='quiz_start_api'),
    path('quiz/api/answer/', views.quiz_answer_api_view, name='quiz_answer_api'),
    path('quiz/api/state/', views.quiz_state_api_view, name='quiz_state_api'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('suggestions/', views.suggestions_review_view, name='suggestions_review'),
    path('suggestions/mine/', views.my_suggestions_view, name='my_suggestions'),
    path('suggestions/submit/', views.suggestion_submit_view, name='suggestion_submit'),
    path('suggestions/publish/', views.suggestion_publish_view, name='suggestion_publish'),
    path('suggestions/<int:suggestion_id>/approve/', views.suggestion_approve_view, name='suggestion_approve'),
    path('suggestions/<int:suggestion_id>/reject/', views.suggestion_reject_view, name='suggestion_reject'),
    path('about/', views.about_view, name='about'),
    path('awards/', views.awards_view, name='awards_list'),
    path('salaries/', views.salaries_view, name='salaries_list'),
    path('compare/', views.compare_players_view, name='compare_players'),
    path('compare/selection/', views.compare_selection_view, name='compare_selection'),
    path('graph/', views.graph_view, name='graph_view'),
    path('halloffame/', views.hall_of_fame_view, name='hall_of_fame'),
    path('managers/', views.managers_view, name='managers_list'),
]
